import {C} from "./config.js";
export default function EditView({activePage,activeIdx,pages,filter,setFilter,brightness,setBrightness,contrast,setContrast,saveEdit,rotatePage,deletePage,setMode,setActiveIdx}){
return(<div style={{height:"100vh",background:C.bg,display:"flex",flexDirection:"column",fontFamily:"'Inter',sans-serif"}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"14px 20px",borderBottom:"1px solid "+C.border}}>
<button className="ds-btn" onClick={()=>{setMode("gallery");setActiveIdx(null)}} style={{background:"none",color:C.muted,fontSize:15,padding:"6px 0"}}>← Back</button>
<span style={{fontSize:13,color:C.muted,fontWeight:500}}>{activeIdx+1}/{pages.length}</span>
<button className="ds-btn" onClick={saveEdit} style={{background:C.accent,color:C.white,padding:"8px 22px",borderRadius:10,fontSize:13,fontWeight:600}}>Save</button></div>
<div style={{flex:1,display:"flex",alignItems:"center",justifyContent:"center",overflow:"hidden",padding:16,background:"#080A0E"}}>
<img src={activePage.src} style={{maxWidth:"92%",maxHeight:"100%",objectFit:"contain",borderRadius:6,transform:"rotate("+activePage.rotation+"deg)",filter:"brightness("+brightness+"%) contrast("+contrast+"%)"+( filter==="grayscale"?" grayscale(1)":filter==="highcontrast"?" grayscale(1) contrast(200%) brightness(120%)":filter==="sharpen"?" contrast(130%) brightness(105%)":""),transition:"filter 0.2s,transform 0.3s"}}/></div>
<div style={{padding:"16px 20px 28px",borderTop:"1px solid "+C.border,background:C.surface}}>
<div style={{display:"flex",gap:8,marginBottom:18,overflowX:"auto"}}>{[{key:"original",label:"Original"},{key:"grayscale",label:"B&W"},{key:"highcontrast",label:"Document"},{key:"sharpen",label:"Sharp"}].map(f=>(<button key={f.key} className="ds-btn" onClick={()=>setFilter(f.key)} style={{padding:"10px 18px",borderRadius:12,fontSize:12,fontWeight:600,whiteSpace:"nowrap",background:filter===f.key?C.accent:C.surface2,color:filter===f.key?C.white:C.muted,border:filter===f.key?"none":"1px solid "+C.border}}>{f.label}</button>))}</div>
<div style={{display:"flex",gap:20,marginBottom:16}}><div style={{flex:1}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><span style={{fontSize:12,color:C.muted}}>Brightness</span><span style={{fontSize:12,color:C.text,fontWeight:600}}>{brightness}%</span></div><input type="range" min="30" max="200" value={brightness} onChange={e=>setBrightness(+e.target.value)}/></div><div style={{flex:1}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><span style={{fontSize:12,color:C.muted}}>Contrast</span><span style={{fontSize:12,color:C.text,fontWeight:600}}>{contrast}%</span></div><input type="range" min="30" max="200" value={contrast} onChange={e=>setContrast(+e.target.value)}/></div></div>
<div style={{display:"flex",gap:10}}><button className="ds-btn" onClick={()=>rotatePage(activeIdx)} style={{flex:1,padding:"12px",background:C.surface2,color:C.text,borderRadius:10,fontSize:14,fontWeight:500,border:"1px solid "+C.border}}>↻ Rotate</button><button className="ds-btn" onClick={()=>deletePage(activeIdx)} style={{flex:1,padding:"12px",background:"#1C1015",color:C.danger,borderRadius:10,fontSize:14,fontWeight:500,border:"1px solid #3D1A1A"}}>✕ Delete</button></div></div></div>)}
